### ISSUE TITLE
Old post (after payout) is signed as "correct"

### ISSUE THREAD

**Issue by lukmarcus** [noisy-witness/steem-wise-voter-page#12]
Older posts (after 7 days so after payouts) after url paste should be signed as `THIS IS NOT CORRECT - POST TOO OLD TO VOTE` instead of `This is correct`. This info could also appear after `validate`.

![](https://cdn.steemitimages.com/DQmZqMRSS2xHTXtpxn7ww6JekYNNpX8dSW1kPX2cY1rDMjg/obraz.png)

In my opinion Wise should vote only for active posts.

**Comment by Jblew** [comment]
This behaviour is intentional. Voting is not only for $$. Sometimes it is nice to show appreciation even if it does not mean countable profit. I've created the AgeOfPost rule (https://github.com/noisy-witness/steem-wise-core/issues/4) which allows limiting voting to posts no older than seven days.
