### ISSUE TITLE
No information if post was already voted

### ISSUE THREAD

**Issue by lukmarcus** [noisy-witness/steem-wise-voter-page#13]
There should be an information if delegator has already voted for post from link. This could happen after url paste or after `validate`.

![](https://cdn.steemitimages.com/DQmWcgMMkDUvA7QNhTBn9feKJe6CvLf4DSMr9noufxRWCZn/obraz.png)

**Comment by lukmarcus** [comment]
This should be listed as `bug`. With 2nd/3rd etc. vote you can change height of previous upvotes:

![](https://cdn.steemitimages.com/DQmRoSqvNaaTHmqBjodZeAhLqXu8uemamHwMkfkWQB52yUH/obraz.png)

Voting AGAIN should be possible only with bigger vote power and still there should be information after `validate` like `this post was already voted by voter X with Y% of delegate Z`.

**Comment by jakipatryk** [comment]
@lukmarcus Does re-vote consume voting power? I'm sure it cancels curation reward tho, so it's not good for delegator.

I'm not sure if this is frontend issue at all, maybe this problem should be fixed in the core library?

On the other hand, the voter might want to downvote a post that has already been upvoted by a delegator, because he/she found the post a plagiarism or something.

I can work on this issue.

**Comment by lukmarcus** [comment]
@jakipatryk 
>Does re-vote consume voting power?

Lower vote didn't consume power. I didn't check it for higher vote - but it looked like only percent difference was taken from account.

>the voter might want to downvote a post

It's not as easy as it sounds because it works two ways - you can flag a vote or vote a flag. I forgot about that. So... Can voter change vote power? If yes, we must answer some questions:
1. Can voter change a vote/flag from delegator?
2. Can vote/flag be changed up, down or both?
3. Can vote be changed into flag and the other way?

Maybe there should be something like hierarchy of voters? So one voter can only change something from below and not above?

**Comment by jakipatryk** [comment]
I think a hierarchy of voters might be a bit too complicated at this point. IMO overwriting a vote should be disabled by default, but there should be a *rule* (or *rules*?) to let delegator enable doing it for certain voters, example rule could look like this:

```
{
    "rule": "overwrite_vote",
    "mode": "decrease_vote_weight", // or "increase_vote_weight", or "both", determines whether voter can increase a vote weight, decrease, or do both
    "when": "is_downvote" // or "is_upvote", or "is_any", determines when voter can overwrite a vote (when it's upvote, when it's downvote, or when it's either of them
    "times": "once" // or "twice", or "any", determines how many times a voter can overwrite a vote on one single post, I'm not sure if it's needed tho
}
```

What do you think? @lukmarcus

**Comment by lukmarcus** [comment]
It's a nice solution. I like it.

But still going back to first problem - there should be an information that post was already voted by delegator.
