### ISSUE TITLE
Support for SteemConnect

### ISSUE THREAD

**Issue by noisy** [noisy-witness/steem-wise-voter-page#8]
Users should be able to use VoterPage without a need of pasting manually a private posting key.

Useful links:
- https://github.com/steemit/steemconnect
- [How to configure SteemConnect v2 and use it with your application.](https://steemit.com/steemconnect/@noisy/how-to-configure-steemconnect-v2-and-use-it-with-your-application-how-it-works-and-how-it-is-different-from-v1)

**Comment by Jblew** [comment]
Done
